improved deploy procedure, now gives propper errors describing what failed

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -21,15 +21,30 @@ if [ ! -f "$conf_file" ]; then
     exit 1
 fi
 
-dest="$(cat "$conf_file")"
+d_dest="$(cat "$conf_file")"
 
-if [ ! -d "$dest" ]; then
+if [ ! -d "$d_dest" ]; then
     echo "ERROR: The directory mentioned in .destination does not exist"
-    echo "       Supplied destination: $dest"
+    echo "       Supplied destination: $d_dest"
     exit 1
 fi
 
 echo
 echo "-----   Deploying man_asdf   -----"
 
-rsync -ahP --inplace  "$CURRENT_DIR"/man_asdf "$dest"
+cmd_man="man_asdf"
+f_src="$CURRENT_DIR/$cmd_man"
+f_man_asdf="$d_dest/$cmd_man"
+f_man="$d_dest"/man
+
+rsync -ahP --inplace  "$f_src" "$f_man_asdf" | grep -v "sending incremental file list"
+if [ -f "$f_man_asdf" ]; then
+    ln -sf "f_man_asdf" "$f_man"
+    [ -L "$f_man" ] || {
+        echo "ERROR: failed to create symbolick link $f_man"
+        exit 1
+    }
+else
+    echo "ERROR: failed deploy to: $f_man_asdf"
+    exit 1
+fi
